"""GuruFocus API client library.

A Python client for the GuruFocus API with async support,
Pydantic models, and intelligent caching.
"""

from .client import GuruFocusClient
from .config import GuruFocusSettings
from .exceptions import (
    APIError,
    AuthenticationError,
    GuruFocusError,
    InvalidSymbolError,
    NetworkError,
    NotFoundError,
    RateLimitError,
    ValidationError,
)
from .logging import configure_from_settings, configure_logging, get_logger, is_otel_available
from .models import (
    AnalystEstimates,
    DividendHistory,
    DividendMetrics,
    DividendPayment,
    EfficiencyRatios,
    EstimatePeriod,
    FilterBuilder,
    FilterOperator,
    FinancialPeriod,
    FinancialRatios,
    FinancialStatements,
    GeneralInfo,
    GrowthEstimates,
    GrowthRatios,
    GuruHolding,
    GuruInfo,
    GuruList,
    GuruPicks,
    GuruTrade,
    GuruTrades,
    InsiderTrade,
    InsiderTrades,
    InstitutionalActivity,
    KeyRatios,
    LiquidityRatios,
    PerShareData,
    PriceHistory,
    PriceMetrics,
    PricePoint,
    ProfitabilityRatios,
    QualityScores,
    RatioHistory,
    RatioIndustry,
    RatioValue,
    ScreenerFilter,
    ScreenerRequest,
    ScreenerResults,
    ScreenerSort,
    ScreenerStock,
    SolvencyRatios,
    StockGuruHolder,
    StockGurus,
    StockSummary,
    ValuationMetrics,
    ValuationRatios,
    deep_value_filters,
    dividend_filters,
    growth_filters,
    quality_filters,
    value_filters,
)
from .rate_limiter import NullRateLimiter, RateLimitConfig, RateLimiter

__version__ = "0.1.0"
__all__ = [
    "APIError",
    "AnalystEstimates",
    "AuthenticationError",
    "DividendHistory",
    "DividendMetrics",
    "DividendPayment",
    "EfficiencyRatios",
    "EstimatePeriod",
    "FilterBuilder",
    "FilterOperator",
    "FinancialPeriod",
    "FinancialRatios",
    "FinancialStatements",
    "GeneralInfo",
    "GrowthEstimates",
    "GrowthRatios",
    "GuruFocusClient",
    "GuruFocusError",
    "GuruFocusSettings",
    "GuruHolding",
    "GuruInfo",
    "GuruList",
    "GuruPicks",
    "GuruTrade",
    "GuruTrades",
    "InsiderTrade",
    "InsiderTrades",
    "InstitutionalActivity",
    "InvalidSymbolError",
    "KeyRatios",
    "LiquidityRatios",
    "NetworkError",
    "NotFoundError",
    "NullRateLimiter",
    "PerShareData",
    "PriceHistory",
    "PriceMetrics",
    "PricePoint",
    "ProfitabilityRatios",
    "QualityScores",
    "RateLimitConfig",
    "RateLimitError",
    "RateLimiter",
    "RatioHistory",
    "RatioIndustry",
    "RatioValue",
    "ScreenerFilter",
    "ScreenerRequest",
    "ScreenerResults",
    "ScreenerSort",
    "ScreenerStock",
    "SolvencyRatios",
    "StockGuruHolder",
    "StockGurus",
    "StockSummary",
    "ValidationError",
    "ValuationMetrics",
    "ValuationRatios",
    "__version__",
    "configure_from_settings",
    "configure_logging",
    "deep_value_filters",
    "dividend_filters",
    "get_logger",
    "growth_filters",
    "is_otel_available",
    "quality_filters",
    "value_filters",
]
